services:
  adcu:
    image: josegamen/app-adcu:latest
    container_name: app-adcu
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://adcuUser:adcuPass123@mongo-adcu:27017/ADCU
      - JWT_SECRET=AxOp1Yuero91202kdh12
      - PORT=5000
      - HOST=0.0.0.0
      - KEYCHATGPT=api-key-placeholder
    networks:
      - adcu-network

volumes:
  adcu-data:
  
networks:
  adcu-network: 
    external: true