services:
  mongo:
    image: josegamen/mongo-adcu
    container_name: mongo-adcu
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "adcunumber1"
      MONGO_INITDB_DATABASE: adcu
    volumes:
      - mongo-data:/data/db
    networks:
      - adcu-network
volumes:
  mongo-data:

networks:
  adcu-network: 
    external: true